var dir_b5ca23d60d924ae7687ba48a389d1f3c =
[
    [ "hri_ac_d21d.h", "hri__ac__d21d_8h.html", null ],
    [ "hri_adc_d21d.h", "hri__adc__d21d_8h.html", null ],
    [ "hri_d21d.h", "hri__d21d_8h.html", null ],
    [ "hri_dac_d21d.h", "hri__dac__d21d_8h.html", null ],
    [ "hri_dmac_d21d.h", "hri__dmac__d21d_8h.html", null ],
    [ "hri_dsu_d21d.h", "hri__dsu__d21d_8h.html", null ],
    [ "hri_eic_d21d.h", "hri__eic__d21d_8h.html", null ],
    [ "hri_evsys_d21d.h", "hri__evsys__d21d_8h.html", null ],
    [ "hri_gclk_d21d.h", "hri__gclk__d21d_8h.html", null ],
    [ "hri_hmatrixb_d21d.h", "hri__hmatrixb__d21d_8h.html", null ],
    [ "hri_i2s_d21d.h", "hri__i2s__d21d_8h.html", null ],
    [ "hri_mtb_d21d.h", "hri__mtb__d21d_8h.html", null ],
    [ "hri_nvic_d21d.h", "hri__nvic__d21d_8h.html", null ],
    [ "hri_nvmctrl_d21d.h", "hri__nvmctrl__d21d_8h.html", null ],
    [ "hri_pac_d21d.h", "hri__pac__d21d_8h.html", null ],
    [ "hri_pm_d21d.h", "hri__pm__d21d_8h.html", null ],
    [ "hri_port_d21d.h", "hri__port__d21d_8h.html", null ],
    [ "hri_rtc_d21d.h", "hri__rtc__d21d_8h.html", null ],
    [ "hri_sercom_d21d.h", "hri__sercom__d21d_8h.html", null ],
    [ "hri_sysctrl_d21d.h", "hri__sysctrl__d21d_8h.html", null ],
    [ "hri_systemcontrol_d21d.h", "hri__systemcontrol__d21d_8h.html", null ],
    [ "hri_systick_d21d.h", "hri__systick__d21d_8h.html", null ],
    [ "hri_tc_d21d.h", "hri__tc__d21d_8h.html", null ],
    [ "hri_tcc_d21d.h", "hri__tcc__d21d_8h.html", null ],
    [ "hri_usb_d21d.h", "hri__usb__d21d_8h.html", null ],
    [ "hri_wdt_d21d.h", "hri__wdt__d21d_8h.html", null ]
];