var modules =
[
    [ "CMSIS Global Defines", "group___c_m_s_i_s__glob__defs.html", null ],
    [ "Defines and Type Definitions", "group___c_m_s_i_s__core__register.html", "group___c_m_s_i_s__core__register" ],
    [ "SAMD21 Device Definitions", "group___s_a_m_d21__definitions.html", "group___s_a_m_d21__definitions" ],
    [ "CMSIS Definitions", "group___s_a_m_d21_e17_d__cmsis.html", null ],
    [ "Peripheral Software API", "group___s_a_m_d21_e17_d__api.html", null ],
    [ "Registers Access Definitions", "group___s_a_m_d21_e17_d__reg.html", null ],
    [ "Peripheral Ids Definitions", "group___s_a_m_d21_e17_d__id.html", null ],
    [ "Peripheral Base Address Definitions", "group___s_a_m_d21_e17_d__base.html", null ],
    [ "PORT Definitions", "group___s_a_m_d21_e17_d__port.html", null ],
    [ "CMSIS Definitions", "group___s_a_m_d21_e17_d_u__cmsis.html", null ],
    [ "Peripheral Software API", "group___s_a_m_d21_e17_d_u__api.html", null ],
    [ "Registers Access Definitions", "group___s_a_m_d21_e17_d_u__reg.html", null ],
    [ "Peripheral Ids Definitions", "group___s_a_m_d21_e17_d_u__id.html", null ],
    [ "Peripheral Base Address Definitions", "group___s_a_m_d21_e17_d_u__base.html", null ],
    [ "PORT Definitions", "group___s_a_m_d21_e17_d_u__port.html", null ],
    [ "CMSIS Definitions", "group___s_a_m_d21_e17_l__cmsis.html", null ],
    [ "Peripheral Software API", "group___s_a_m_d21_e17_l__api.html", null ],
    [ "Registers Access Definitions", "group___s_a_m_d21_e17_l__reg.html", null ],
    [ "Peripheral Ids Definitions", "group___s_a_m_d21_e17_l__id.html", null ],
    [ "Peripheral Base Address Definitions", "group___s_a_m_d21_e17_l__base.html", null ],
    [ "PORT Definitions", "group___s_a_m_d21_e17_l__port.html", null ],
    [ "CMSIS Definitions", "group___s_a_m_d21_g17_d__cmsis.html", null ],
    [ "Peripheral Software API", "group___s_a_m_d21_g17_d__api.html", null ],
    [ "Registers Access Definitions", "group___s_a_m_d21_g17_d__reg.html", null ],
    [ "Peripheral Ids Definitions", "group___s_a_m_d21_g17_d__id.html", null ],
    [ "Peripheral Base Address Definitions", "group___s_a_m_d21_g17_d__base.html", null ],
    [ "PORT Definitions", "group___s_a_m_d21_g17_d__port.html", null ],
    [ "CMSIS Definitions", "group___s_a_m_d21_g17_l__cmsis.html", null ],
    [ "Peripheral Software API", "group___s_a_m_d21_g17_l__api.html", null ],
    [ "Registers Access Definitions", "group___s_a_m_d21_g17_l__reg.html", null ],
    [ "Peripheral Ids Definitions", "group___s_a_m_d21_g17_l__id.html", null ],
    [ "Peripheral Base Address Definitions", "group___s_a_m_d21_g17_l__base.html", null ],
    [ "PORT Definitions", "group___s_a_m_d21_g17_l__port.html", null ],
    [ "CMSIS Definitions", "group___s_a_m_d21_j17_d__cmsis.html", null ],
    [ "Peripheral Software API", "group___s_a_m_d21_j17_d__api.html", null ],
    [ "Registers Access Definitions", "group___s_a_m_d21_j17_d__reg.html", null ],
    [ "Peripheral Ids Definitions", "group___s_a_m_d21_j17_d__id.html", null ],
    [ "Peripheral Base Address Definitions", "group___s_a_m_d21_j17_d__base.html", null ],
    [ "PORT Definitions", "group___s_a_m_d21_j17_d__port.html", null ],
    [ "Doc_driver_hal_adc_sync", "group__doc__driver__hal__adc__sync.html", "group__doc__driver__hal__adc__sync" ],
    [ "Doc_driver_hal_helper_atomic", "group__doc__driver__hal__helper__atomic.html", "group__doc__driver__hal__helper__atomic" ],
    [ "Delay Driver", "group__doc__driver__hal__delay.html", "group__doc__driver__hal__delay" ],
    [ "Doc_driver_hal_ext_irq", "group__doc__driver__hal__ext__irq.html", "group__doc__driver__hal__ext__irq" ],
    [ "Init Driver", "group__doc__driver__hal__helper__init.html", "group__doc__driver__hal__helper__init" ],
    [ "I/O Driver", "group__doc__driver__hal__helper__io.html", "group__doc__driver__hal__helper__io" ],
    [ "Doc_driver_hal_pwm_async", "group__doc__driver__hal__pwm__async.html", "group__doc__driver__hal__pwm__async" ],
    [ "Doc_driver_hal_helper_sleep", "group__doc__driver__hal__helper__sleep.html", "group__doc__driver__hal__helper__sleep" ],
    [ "Doc_driver_hal_spi_master_sync", "group__doc__driver__hal__spi__master__sync.html", "group__doc__driver__hal__spi__master__sync" ],
    [ "Doc_driver_hal_timer", "group__doc__driver__hal__timer.html", "group__doc__driver__hal__timer" ],
    [ "ADC", "group___h_p_l.html", "group___h_p_l" ],
    [ "HPL SPI", "group__hpl__spi.html", "group__hpl__spi" ],
    [ "Doc_driver_hal_utils_macro", "group__doc__driver__hal__utils__macro.html", "group__doc__driver__hal__utils__macro" ],
    [ "Doc_driver_hal_utils_list", "group__doc__driver__hal__utils__list.html", "group__doc__driver__hal__utils__list" ],
    [ "GCLK Hardware Proxy Layer", "group__gclk__group.html", "group__gclk__group" ],
    [ "PM Low Level Driver Helpers", "group__pm__group.html", "group__pm__group" ],
    [ "TC Hardware Proxy Layer", "group__tc__group.html", "group__tc__group" ],
    [ "TCC Low Level Driver Helpers", "group__tcc__group.html", "group__tcc__group" ],
    [ "Analog Comparators", "group___s_a_m_d21___a_c.html", null ],
    [ "Analog Digital Converter", "group___s_a_m_d21___a_d_c.html", null ],
    [ "Digital Analog Converter", "group___s_a_m_d21___d_a_c.html", null ],
    [ "Direct Memory Access Controller", "group___s_a_m_d21___d_m_a_c.html", null ],
    [ "Device Service Unit", "group___s_a_m_d21___d_s_u.html", null ],
    [ "External Interrupt Controller", "group___s_a_m_d21___e_i_c.html", null ],
    [ "Event System Interface", "group___s_a_m_d21___e_v_s_y_s.html", null ],
    [ "Generic Clock Generator", "group___s_a_m_d21___g_c_l_k.html", null ],
    [ "HSB Matrix", "group___s_a_m_d21___h_m_a_t_r_i_x_b.html", null ],
    [ "Inter-IC Sound Interface", "group___s_a_m_d21___i2_s.html", null ],
    [ "Cortex-M0+ Micro-Trace Buffer", "group___s_a_m_d21___m_t_b.html", null ],
    [ "Non-Volatile Memory Controller", "group___s_a_m_d21___n_v_m_c_t_r_l.html", null ],
    [ "Peripheral Software API", "group__fuses__api.html", null ],
    [ "Peripheral Access Controller", "group___s_a_m_d21___p_a_c.html", null ],
    [ "Power Manager", "group___s_a_m_d21___p_m.html", null ],
    [ "Port Module", "group___s_a_m_d21___p_o_r_t.html", null ],
    [ "Real-Time Counter", "group___s_a_m_d21___r_t_c.html", null ],
    [ "Serial Communication Interface", "group___s_a_m_d21___s_e_r_c_o_m.html", null ],
    [ "System Control", "group___s_a_m_d21___s_y_s_c_t_r_l.html", null ],
    [ "Basic Timer Counter", "group___s_a_m_d21___t_c.html", null ],
    [ "Timer Counter Control", "group___s_a_m_d21___t_c_c.html", null ],
    [ "Universal Serial Bus", "group___s_a_m_d21___u_s_b.html", null ],
    [ "Watchdog Timer", "group___s_a_m_d21___w_d_t.html", null ]
];