var dir_49aee461ce145ed17c3f72c77731deeb =
[
    [ "xmc1_eru_map.h", "xmc1__eru__map_8h.html", "xmc1__eru__map_8h" ],
    [ "xmc1_flash.h", "xmc1__flash_8h.html", null ],
    [ "xmc1_gpio.h", "xmc1__gpio_8h.html", null ],
    [ "xmc1_gpio_map.h", "xmc1__gpio__map_8h.html", "xmc1__gpio__map_8h" ],
    [ "xmc1_rtc.h", "xmc1__rtc_8h.html", "xmc1__rtc_8h" ],
    [ "xmc1_scu.h", "xmc1__scu_8h.html", null ],
    [ "xmc1_usic_map.h", "xmc1__usic__map_8h.html", "xmc1__usic__map_8h" ],
    [ "xmc_acmp.h", "xmc__acmp_8h.html", null ],
    [ "xmc_bccu.h", "xmc__bccu_8h.html", null ],
    [ "xmc_ccu4.h", "xmc__ccu4_8h.html", "xmc__ccu4_8h" ],
    [ "xmc_ccu4_map.h", "xmc__ccu4__map_8h.html", "xmc__ccu4__map_8h" ],
    [ "xmc_ccu8.h", "xmc__ccu8_8h.html", null ],
    [ "xmc_ccu8_map.h", "xmc__ccu8__map_8h.html", "xmc__ccu8__map_8h" ],
    [ "xmc_common.h", "xmc__common_8h.html", "xmc__common_8h" ],
    [ "xmc_device.h", "xmc__device_8h.html", "xmc__device_8h" ],
    [ "xmc_eru.h", "xmc__eru_8h.html", "xmc__eru_8h" ],
    [ "xmc_flash.h", "xmc__flash_8h.html", "xmc__flash_8h" ],
    [ "xmc_gpio.h", "xmc__gpio_8h.html", "xmc__gpio_8h" ],
    [ "xmc_i2c.h", "xmc__i2c_8h.html", "xmc__i2c_8h" ],
    [ "xmc_ledts.h", "xmc__ledts_8h.html", null ],
    [ "xmc_math.h", "xmc__math_8h.html", null ],
    [ "xmc_pau.h", "xmc__pau_8h.html", null ],
    [ "xmc_posif.h", "xmc__posif_8h.html", null ],
    [ "xmc_prng.h", "xmc__prng_8h.html", null ],
    [ "xmc_rtc.h", "xmc__rtc_8h.html", "xmc__rtc_8h" ],
    [ "xmc_scu.h", "xmc__scu_8h.html", "xmc__scu_8h" ],
    [ "xmc_spi.h", "xmc__spi_8h.html", "xmc__spi_8h" ],
    [ "xmc_uart.h", "xmc__uart_8h.html", "xmc__uart_8h" ],
    [ "xmc_usic.h", "xmc__usic_8h.html", "xmc__usic_8h" ],
    [ "xmc_vadc.h", "xmc__vadc_8h.html", "xmc__vadc_8h" ],
    [ "xmc_vadc_map.h", "xmc__vadc__map_8h.html", "xmc__vadc__map_8h" ],
    [ "xmc_wdt.h", "xmc__wdt_8h.html", "xmc__wdt_8h" ]
];