var dir_5fb89c1e2b594cf30f259bb8eed09d76 =
[
    [ "xmc1_eru.c", "xmc1__eru_8c.html", "xmc1__eru_8c" ],
    [ "xmc1_flash.c", "xmc1__flash_8c.html", "xmc1__flash_8c" ],
    [ "xmc1_gpio.c", "xmc1__gpio_8c.html", "xmc1__gpio_8c" ],
    [ "xmc1_rtc.c", "xmc1__rtc_8c.html", "xmc1__rtc_8c" ],
    [ "xmc1_scu.c", "xmc1__scu_8c.html", "xmc1__scu_8c" ],
    [ "xmc1_usic.c", "xmc1__usic_8c.html", "xmc1__usic_8c" ],
    [ "xmc_acmp.c", "xmc__acmp_8c.html", null ],
    [ "xmc_bccu.c", "xmc__bccu_8c.html", null ],
    [ "xmc_ccu4.c", "xmc__ccu4_8c.html", "xmc__ccu4_8c" ],
    [ "xmc_ccu8.c", "xmc__ccu8_8c.html", null ],
    [ "xmc_common.c", "xmc__common_8c.html", "xmc__common_8c" ],
    [ "xmc_eru.c", "xmc__eru_8c.html", "xmc__eru_8c" ],
    [ "xmc_gpio.c", "xmc__gpio_8c.html", "xmc__gpio_8c" ],
    [ "xmc_i2c.c", "xmc__i2c_8c.html", "xmc__i2c_8c" ],
    [ "xmc_ledts.c", "xmc__ledts_8c.html", null ],
    [ "xmc_math.c", "xmc__math_8c.html", null ],
    [ "xmc_pau.c", "xmc__pau_8c.html", null ],
    [ "xmc_posif.c", "xmc__posif_8c.html", null ],
    [ "xmc_prng.c", "xmc__prng_8c.html", null ],
    [ "xmc_rtc.c", "xmc__rtc_8c.html", "xmc__rtc_8c" ],
    [ "xmc_spi.c", "xmc__spi_8c.html", "xmc__spi_8c" ],
    [ "xmc_uart.c", "xmc__uart_8c.html", "xmc__uart_8c" ],
    [ "xmc_usic.c", "xmc__usic_8c.html", "xmc__usic_8c" ],
    [ "xmc_vadc.c", "xmc__vadc_8c.html", "xmc__vadc_8c" ],
    [ "xmc_wdt.c", "xmc__wdt_8c.html", "xmc__wdt_8c" ]
];